# Generated by Django 5.0.2 on 2024-02-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_orderitem_order_order_order_item'),
        ('product', '0002_remove_product_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, related_name='order_items_set', to='product.product'),
        ),
    ]
