# Generated by Django 5.0.2 on 2024-02-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_orderitem_product'),
        ('product', '0002_remove_product_order_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ManyToManyField(related_name='order_items_set', to='product.product'),
        ),
    ]
