# Generated by Django 5.0.2 on 2024-03-13 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_refferal_user_user_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='refferal_code',
            field=models.CharField(default=datetime.datetime(2024, 3, 13, 14, 18, 4, 303737, tzinfo=datetime.timezone.utc), max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
